### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ElliChuang**
老師晚安，我是莊霈虹(Elli)，以下是我已上線 API 的網址，謝謝!!
http://54.64.106.13:3000/api/attractions?page=1
http://54.64.106.13:3000/api/attractions?page=0&keyword=藝文館所
http://54.64.106.13:3000/api/attractions?page=0&keyword=北
http://54.64.106.13:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — DISMISSED** [review]
OK. Done.

But suggest using `GROUP_CONCAT` and `JOIN` to get attraction data and images all at once, not get images one by one, it's expensive operations.

**Comment by ElliChuang** [comment]
老師午安，有關image存取，我用 inner join 與 group_concat 的方式重新修正了程式碼，麻煩老師 review，謝謝!!

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — APPROVED** [review]
Good Improvement.

**Pull request merged**
